server: 
      port: 4343
      servlet.context-path: /RestSwaggerApi
spring:
     datasource:
              driverClassName: oracle.jdbc.driver.OracleDriver
              url: jdbc:oracle:thin:@localhost:1521:xe
              username: system
              password: amit
     show_sql: true
     hbm2ddl.auto: update