server:
    port: 4343
    context-path: /LoginBoot
spring:
     mvc:
       view:
          prefix: /
          suffix: .jsp
     datasource:
             driverClassName: oracle.jdbc.driver.OracleDriver
             url: jdbc:oracle:thin:@localhost:1521:xe
             username: system
             password: amit 