server: 
      port: 4142
      context-path: /RestCurdApi
spring:
     datasource:
              driverClassName: oracle.jdbc.driver.OracleDriver
              url: jdbc:oracle:thin:@localhost:1521:xe
              username: system
              password: amit
     show_sql: true
     hbm2ddl.auto: update